# Generated by Django 6.1 on 2026-09-09 08:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("organization", models.CharField(max_length=255)),
                ("context_label", models.CharField(blank=True, max_length=255)),
                ("summary", models.TextField()),
                ("contribution", models.TextField()),
                (
                    "technologies",
                    models.TextField(
                        blank=True, help_text="Enter one technology or topic per line."
                    ),
                ),
                ("award", models.CharField(blank=True, max_length=255)),
                ("is_featured", models.BooleanField(default=False)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-is_featured", "display_order", "title"],
            },
        ),
    ]
