# Generated by Django 6.1 on 2026-09-09 10:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="organization",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="experience",
            name="role_timeline",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="experience",
            name="category",
            field=models.CharField(
                choices=[
                    ("internship", "Internship"),
                    ("research", "Research"),
                    ("volunteer", "Volunteer"),
                    ("part-time", "Part-Time"),
                    ("full-time", "Full-Time"),
                    ("freelance", "Freelance"),
                    ("intern-working", "Intern & Working Student"),
                ],
                default="full-time",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="experience",
            name="started_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
